version: "3"

networks:
  tango:
    driver: bridge

volumes:
  mongodb: {}

services:
  tango-test:
    build: tango-test
    networks:
      - tango
    environment:
      - TANGO_HOST=tangobox:10000
      - WAIT_HOSTS=tangobox:10000
  tangogql:
    build: tangogql
    networks:
      - tango
    restart: always
    environment:
      - TANGO_HOST=tangobox:10000
    volumes:
      - ./config.json:/tangogql/config.json:ro
    labels:
      - "traefik.frontend.rule=Host:localhost; PathPrefix: /testdb/db, /testdb/socket, /testdb/graphiql; ReplacePathRegex: ^/testdb/((?:db|socket|graphiql.*?)/?)/?$$ /$$1"
      - "traefik.port=5004"
  taranta:
    build: taranta
    networks:
      - tango
    depends_on:
      - tangogql
      - auth
      - dashboards
    labels:
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=80"
  auth:
    build: taranta-auth
    networks:
      - tango
    environment:
      - SECRET=s3cr3t
    volumes:
      - ./users.json:/var/users.json:ro
    labels:
      - "traefik.frontend.rule=Host:localhost; PathPrefixStrip: /auth"
      - "traefik.port=8080"
  dashboards:
    build: taranta-dashboard
    networks:
      - tango
    environment:
      - MONGO_HOST=mongodb://mongodb/dashboards
      - SECRET=s3cr3t
    depends_on:
      - mongodb
    labels:
      - "traefik.frontend.rule=Host:localhost; PathPrefix: /dashboards"
      - "traefik.port=3012"
  mongodb:
    image: mongo:3.6-stretch
    networks:
      - tango
    volumes:
      - mongodb:/data/db
  traefik:
    image: traefik:1.7-alpine
    networks:
      - tango
    command: --docker
    ports:
      - 22484:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
